### ISSUE TITLE
Open Definition does not work in Safari

### ISSUE THREAD

**Issue by dennis-behm** [IBM/zopeneditor-sample#3]
Wazi Technology Preview Feedback

@Isabel.arnold and I are currently experimenting with WAZI and found an issue with the Open Definition with the SAM1.cbl. It does work with Firefox, but not with Safari.

Hover over the field works fine, but to jump to the declaration does not.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/28918869/50635974-a3b92480-0f54-11e9-90b0-d8dae49ce3c8.png">

**Comment by prajapatiprasangibm** [comment]
Hi @dennis-behm 
Thank you for your feedback. I was looking for the issue and basically it only works when you do single click on the variable, by double clicking it and selecting the variable, go to definition will not work.

![2019-01-03 10 20 20](https://user-images.githubusercontent.com/42014219/50645316-42d42100-0f41-11e9-8149-767c153405b8.gif)


Let us know if you still not get the definition.

**Comment by dennis-behm** [comment]
Thanks for verifying it. Will close the issue.
