### ISSUE TITLE
VSCode extension tutorial - minor clarification on populating COBOL sample dataset members

### ISSUE THREAD

**Issue by UkRobJones** [IBM/zopeneditor-sample#6]
In wazi-tutorial/README-VSCODE.md, section “Edit and Submit JCL to compile, link, and run jobs”:
https://github.com/IBM/wazi-tutorial/blob/master/README-VSCODE.md#edit-and-submit-jcl-to-compile-link-and-run-jobs

“	•	For the COBOL and COPYBOOK PDS members, simply use Create New Member method to move files from your workspace to the MVS dataset:
	◦	Create SAM1 and SAM2 members to USER1.SAMPLE.COBOL \
	◦	Create CUSTCOPY, SAM2PARM, TRANREC members to USER1.SAMPLE.COPYLIB”

.. it is not made clear how the user is expected to populate each dataset member (i.e. the "move files" part of Create New Member). For example, by manual copy/paste of the local file editor window contents for each corresponding file. (perhaps there will be drag/drop support in future per the equivalent section in the WAZI tutorial, but for now the intention of the author is not clear here with the VSCode extension)

**Comment by PrasangAPrajapati** [comment]
Hi @UkRobJones 

Thank you so much for creating an issue, going through the tutorial and doing some clarification on our Readme VSCODE. We definitely appreciate such feedback and suggestions. We will surely consider this clarification. 

We are working more towards refining our tutorial and we will push new changes with some refinements soon. Let us know if you have further more questions/suggestions/feedback.

Thanks again.

**Comment by phaumer** [comment]
Refined text with https://github.com/IBM/wazi-tutorial/commit/555a5fc31b50a4d053514a551ebe198cf27bac14
